### ISSUE TITLE
Switch from master to main for primary branch

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint-cli#14]
- [ ] GitHub: Merge any outstanding pull requests
- [ ] Local: Ensure you're up-to-date locally `git fetch && git reset --hard origin/master`
- [ ] Local: Push a `main` branch: `git checkout -b main && git push origin main`
- [ ] GitHub: Under Settings -> Branches: Set the default branch to `main`
- [ ] GitHub: Under Settings -> Branches: Set up branch protection for the `main` branch
- [ ] GitHub: Under Settings -> Branches: Remove branch protection for `master`
- [ ] Local: Delete remote master branch `git push origin :master`
- [ ] Local: Delete master branch `git branch -d master`

**Comment by stephenwade** [comment]
We can do this on the web (https://github.com/github/renaming#renaming-existing-branches).

This has advantages over renaming manually:

> Renaming a branch will:
> 
> - Re-target any open pull requests
> - Update any draft releases based on the branch
> - Move any branch protection rules that explicitly reference the old name
> - Update the branch used to build GitHub Pages, if applicable
> - Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
> - Show a notice to contributors who git push to the old branch
> - Redirect web requests for the old branch name to the new branch name
> - Return a "Moved Permanently" response in API requests for the old branch name

**Comment by nzakas** [comment]
We know. :) The issue just hasn’t been updated since that capability was added.

**Comment by aladdin-add** [comment]
This package is no longer necessary. Use the built-in [`npx`](https://docs.npmjs.com/cli/v8/commands/npx) command instead.
