### ISSUE TITLE
do we still want to maintain the package?

### ISSUE THREAD

**Issue by aladdin-add** [eslint/eslint-cli#17]
the package seems no longer necessary. As of now, something like `npx` has been increasingly popular.
TSC question: do we still want to maintain the package?

**Comment by aladdin-add** [comment]
added "tsc agenda" label, so we can get consensus in the tsc meeting.

**Comment by nzakas** [comment]
Just as a reminder: when you add "tsc agenda" label, please also include a summary and a question.

**Comment by aladdin-add** [comment]
@nzakas , I had edited the description, or should I leave a new comment?

**Comment by aladdin-add** [comment]
Summary: the package seems no longer necessary. As of now, something like npx has been increasingly popular.
TSC question: do we still want to maintain the package?

**Comment by btmills** [comment]
We agreed in the 2021-11-04 TSC meeting that we can stop maintaining this package now that `npx` is available. I will update any docs to direct users to `npx` instead and archive this repository.

**Comment by btmills** [comment]
I didn't find any references to `eslint-cli` in the main eslint/eslint repository or eslint/website. In #18, I added a note to the top of this repository's readme recommending `npx` instead. Once that PR is approved and merged, I'll archive this repository.
