### ISSUE TITLE
Implement `eslint --init`

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint-cli#4]
People can set up ESLint for their project with `eslint --init` command. The command installs `eslint` and necessary plugins into the project local.

However, `eslint-cli` requires local-installed ESLint to use `eslint --init`. This is inconvenient.

    $ eslint --init
    Cannot find local ESLint!
    Please install ESLint by `npm install eslint --save-dev`.

:thinking: though I ran `eslint --init` to install ESLint locally....

**Comment by aladdin-add** [comment]
This package is no longer necessary. Use the built-in [`npx`](https://docs.npmjs.com/cli/v8/commands/npx) command instead.
