### ISSUE TITLE
eslint-cli ignoring plugin:vue/recommended

### ISSUE THREAD

**Issue by bigsee** [eslint/eslint-cli#8]
I am trying to lint my Vue project files using the vue/recommended rules. When I run the linter using npm from within the project folder using

`npm run lint`

..the linter correctly finds 1085 problems and suggests I might want to repair using the --fix option.

However, when I try to do a dry run using eslint-cli with the following command:

`eslint --fix-dry-run --debug --ext .js --ext .vue src`

...only 171 problems are found.

On closer inspection, eslint-cli seems to be picking up all the issues in the vue/strongly-recommended rules, but nothing in recommended. I believe I have the correct configuration in my .eslintrc.js file, which is the following in module.exports:

```js
extends: ['plugin:vue/recommended', 'airbnb-base'],
 plugins: [
   'vue'
 ],
```

...which is presumably why npm catches the errors as expected. However, I notice that when eslint-cli is loading the config files, even though it correctly identifies my choice of rules, it ignores recommended.js and loads all the others:

```
eslint:config Constructing config file hierarchy for /my-project/src +0ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /my-project/.eslintrc.js

  eslint:config-file Loading plugin:vue/recommended +32ms
  eslint:config-file Attempting to resolve eslint-plugin-vue +0ms
  eslint:config-file Loading JS config file: /my-project/node_modules/eslint-plugin-vue/lib/index.js +1ms
  eslint:config-file Loading /my-project/node_modules/eslint-plugin-vue/lib/configs/strongly-recommended.js +5ms
  eslint:config-file Loading JS config file: /my-project/node_modules/eslint-plugin-vue/lib/configs/strongly-recommended.js +0ms
  eslint:config-file Loading /my-project/node_modules/eslint-plugin-vue/lib/configs/essential.js +9ms
  eslint:config-file Loading JS config file: /my-project/node_modules/eslint-plugin-vue/lib/configs/essential.js +0ms
  eslint:config-file Loading /my-project/node_modules/eslint-plugin-vue/lib/configs/base.js +13ms
  eslint:config-file Loading JS config file: /my-project/node_modules/eslint-plugin-vue/lib/configs/base.js +0ms
```

I'm new to eslint-cli so there is an obvious explanation for this, but I've been unable to find it, despite debugging for a while and restarting Webpack numerous times.

Any ideas?

**Comment by aladdin-add** [comment]
This package is no longer necessary. Use the built-in [`npx`](https://docs.npmjs.com/cli/v8/commands/npx) command instead.
